### ISSUE TITLE
Need to start major changes for a public release.

### ISSUE THREAD

**Issue by corbinlc** [CypherpunkArmory/Holepunch-Site#12]
1) Need to add a pricing page.  Lets just start with a Free and a $5/month (will can adjust this later).
2) Signup flow needs to ask a person what pricing they want.
3) Need to add account management.  Things needed..
   a) what email address they are registered to and the ability to change it.
   b) what there current api key is and the ability to generate a new one.
   c) what pricing level they are at and the ability to change it.
   d) ability to delete account.
   e) ability to change the payment info (know that this is needed, but don't work on this yet as we need to sort out what payment providers we use and things like that)
   f) and such

@AndrewScibek and @trip16661 please help me fill this in.

**Comment by corbinlc** [comment]
Please note, that we will want a very very similar setup for UserLAnd and Foxhole.

**Comment by trip16661** [comment]
> Need to add account management. Things needed...

Shouldn't this area also cover the tunnels and other product configuration?

**Comment by corbinlc** [comment]
Those are pretty much all controlled by the CLI, but maybe it could also be controlled from the website.  What do you think @AndrewScibek?

**Comment by corbinlc** [comment]
We talked about this a bit.  We think we would eventually want to have the person be able to see how close they are to limits and also be able to manage their subdomains.  This is not concrete right now, so lets make the flow without it, but know that it will come eventually.

**Comment by corbinlc** [comment]
@trip16661 where do you want to start with this.  Do you want to do some wireframes and submit them on trello so we can get the conversation going?  Do you want to do a call with us first?
Also, for the pricing page, we wanted to add a selection called beta.  It should be the only one they can select now and should say it is free.  How we define the real "free" plan and the first "paid" plan are pending and so we should just have two greyed out options.

**Comment by trip16661** [comment]
@corbinlc  Sure lets do that. I will do a rough mockup of the user settings and we can do a call soon after to review it or add things if necessary.

As for the pricing page, that sounds about right. Do you wish to have a section in the home page as well or it's fine to have just in a separate page?

**Comment by AndrewScibek** [comment]
@trip16661 A separate page would probably be best. Similar to a lot of SaaS companies pricing page
