### ISSUE TITLE
Fix docs formatting for 2 digit (or more) numbered bullet points.

### ISSUE THREAD

**Issue by corbinlc** [CypherpunkArmory/Holepunch-Site#6]
They are not indenting like one digit numbered bullet points.  See EULA page.

**Comment by trip16661** [comment]
This is a common issue whiting the library that I'm using. It has to do with not the library not recognizing new lines inside the bullet point after the first number is a 1 since it takes it as a new list.

For now, I just wrapped it within an OL and LI tags to make it work in #10.
